# Generated by Django 3.2.6 on 2021-08-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изминения')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('place', models.CharField(max_length=150, null=True, verbose_name='Место мероприятия')),
                ('data', models.DateTimeField(verbose_name='Дата и время события')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изминения')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изминения')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('target', models.CharField(max_length=500, verbose_name='Цель')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photos/', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фотографии проектов',
            },
        ),
        migrations.CreateModel(
            name='NewsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_photos/', verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фотографии новостей',
            },
        ),
        migrations.CreateModel(
            name='EventPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/', verbose_name='Изображение')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фото мероприятия',
                'verbose_name_plural': 'Фотографии мероприятий',
            },
        ),
    ]
