# Generated by Django 3.2.6 on 2021-08-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_slider1_slider2_slider3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider1',
            options={'verbose_name': 'Первый слайдер', 'verbose_name_plural': 'Первый слайдер'},
        ),
        migrations.AlterModelOptions(
            name='slider2',
            options={'verbose_name': 'Второй слайдер', 'verbose_name_plural': 'Второй слайдер'},
        ),
        migrations.AlterModelOptions(
            name='slider3',
            options={'verbose_name': 'Третий слайдер', 'verbose_name_plural': 'Третий слайдер'},
        ),
        migrations.AlterField(
            model_name='slider1',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider1', to='blog.projects', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='slider2',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider2', to='blog.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='slider3',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider3', to='blog.event', verbose_name='Мероприятие'),
        ),
    ]
