# Generated by Django 3.2.6 on 2021-09-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210815_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MainNews', to='blog.news', verbose_name='Главная новость')),
            ],
            options={
                'verbose_name': 'Главная новость',
                'verbose_name_plural': 'Главная новость',
            },
        ),
    ]
